apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: monoem/nodeapp:v1
      ports:
        - name : nodeapp
            containerPort: 8080
            protocol: TCP

EOF
